#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'mac_os_x'
cookbook 'dmg'
cookbook 'homebrew'

# Use platform_packages so one can just list packages (from homebrew) to install?
# cookbook 'platform_packages'
